spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # depois sรณ para conectar com o banco
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect